# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

Alexis Cornillon <alexis.cornillon@gmail.com>
Fjolla Qerimi <qerimifjolla7@gmail.com>
